import Link from "next/link"
import { AGE_GROUPS, type ToyFilters } from "@dtc/shared-types/playpuff"
import { listToys } from "@/lib/data/toys"
import { ToyCard } from "./toy-card"

export async function ToyCollection({ filters }: { filters: ToyFilters }) {
  let catalog
  try { catalog = await listToys(filters) } catch { return <div className="pp-wrap pp-section pp-empty"><h1>Let’s try that again.</h1><p>We couldn’t load this collection. Please check your filters or try again shortly.</p><Link className="pp-button" href="/collections/toys">Reset filters</Link></div> }
  const group = AGE_GROUPS.find(g => g.id === filters.age)
  const title = group ? `${group.name} · ${group.label}` : filters.audience === "collectors" ? "Collectors 14+" : filters.audience === "kids" ? "Kids & Family" : "A world of little wonders."
  const form = <form action="/collections/toys" className="pp-filter-form"><label>Who’s playing?<select name="audience" defaultValue={filters.audience ?? ""}><option value="">Everyone</option><option value="kids">Kids & Family</option><option value="collectors">Collectors 14+</option></select></label><label>Shop by age<select name="age" defaultValue={filters.age ?? ""}><option value="">All ages</option>{AGE_GROUPS.map(g => <option key={g.id} value={g.id}>{g.name} · {g.label}</option>)}</select></label><label>Ways to play<select name="category" defaultValue={filters.category ?? ""}><option value="">All categories</option>{catalog.categories.map(c => <option key={c.id} value={c.handle}>{c.name}</option>)}</select></label><div className="pp-price-filter"><label>Min $<input type="number" name="min_price" min="0" step="0.01" defaultValue={filters.min_price} /></label><label>Max $<input type="number" name="max_price" min="0" step="0.01" defaultValue={filters.max_price} /></label></div><label>Sort by<select name="sort" defaultValue={filters.sort ?? "newest"}><option value="newest">Newest first</option><option value="price-asc">Price: low to high</option><option value="price-desc">Price: high to low</option></select></label><label>Search<input type="search" name="q" defaultValue={filters.q} placeholder="Find a little joy" /></label><label className="pp-checkbox"><input type="checkbox" name="in_stock" value="true" defaultChecked={filters.in_stock === "true"} /> In stock only</label><button className="pp-button">Apply filters</button><Link href="/collections/toys">Clear all</Link></form>
  const pages = Math.ceil(catalog.count / 24)
  function href(page: number) { const params = new URLSearchParams(Object.entries(filters).filter(([, v]) => !!v) as [string, string][]); params.set("page", String(page)); return `/collections/toys?${params}` }
  return <div className="pp-wrap pp-section"><p className="pp-eyebrow">FIND YOUR NEXT HAPPY THING</p><h1>{title}</h1><p className="pp-catalog-intro">{catalog.count} {catalog.count === 1 ? "find" : "finds"} · Check each product’s own age recommendation before choosing.</p><div className="pp-catalog-layout"><aside className="pp-filters"><details open><summary>Filter & sort</summary>{form}</details></aside><div>{catalog.products.length ? <div className="pp-product-grid">{catalog.products.map(p => <ToyCard key={p.id} product={p} />)}</div> : <div className="pp-empty"><span aria-hidden="true">✦</span><h2>No matching little wonders yet.</h2><p>Try another age or collection. We only show products with a verified age recommendation in age-filtered results.</p><Link href="/collections/toys">Explore all toys →</Link></div>}<nav className="pp-pagination" aria-label="Pagination">{catalog.page > 1 && <Link href={href(catalog.page - 1)}>← Previous</Link>}{pages > 0 && <span>Page {catalog.page} of {pages}</span>}{catalog.page < pages && <Link href={href(catalog.page + 1)}>Next →</Link>}</nav></div></div></div>
}
