import Image from "next/image"
import Link from "next/link"
import { AGE_GROUPS } from "@dtc/shared-types/playpuff"
import { listToys } from "@/lib/data/toys"
import { ToyCard } from "./toy-card"
import { ToyPicks } from "./toy-picks"
import { ToyVideo } from "./toy-video"

export async function ToyHome() {
  const results = await Promise.allSettled([listToys({ audience: "kids" }), listToys({ audience: "collectors" })])
  const kids = results[0].status === "fulfilled" ? results[0].value : null
  const collectors = results[1].status === "fulfilled" ? results[1].value : null
  const categories = kids?.categories ?? collectors?.categories ?? []
  const grid = (catalog: typeof kids) => catalog?.products.length ? <div className="pp-product-grid">{catalog.products.slice(0, 8).map(p => <ToyCard key={p.id} product={p} />)}</div> : <div className="pp-empty"><span aria-hidden="true">✦</span><h3>{catalog ? "A little more wonder is on the way." : "Our toy shelves are taking a short break."}</h3><p>{catalog ? "We’re getting this collection ready. Explore another age or collection in the meantime." : "The catalog is temporarily unavailable. Please try again shortly."}</p><Link href="/collections/toys">Explore all collections →</Link></div>
  return <div className="pp-home">
    <section className="pp-hero pp-wrap"><div className="pp-hero-copy"><p className="pp-eyebrow">SMALL MOMENTS. BIG DISCOVERIES.</p><h1>A little play.<br />A whole lot<br />of <span>joy.</span><i aria-hidden="true">✦</i></h1><p>Discover toys for growing imaginations and collectibles worth keeping.</p><div className="pp-hero-buttons"><Link className="pp-button" href="/collections/toys?audience=kids">Shop Kids & Family <span aria-hidden="true">↗</span></Link><Link className="pp-text-link" href="/collections/toys?audience=collectors">Explore Collectibles →</Link></div></div><div className="pp-hero-film"><ToyVideo /><div className="pp-film-caption"><span aria-hidden="true">✦</span> A world of play, your way. <span>LET CURIOSITY LEAD</span></div></div></section>
    <div className="pp-wrap pp-audiences"><Link href="/collections/toys?audience=kids"><div><small>FOR LITTLE EXPLORERS</small><h2>Kids & Family</h2><p>Growing minds. Happy little hands.</p></div><span className="pp-shape pp-shape-kids" aria-hidden="true">✦</span><b aria-hidden="true">↗</b></Link><Link href="/collections/toys?audience=collectors"><div><small>FOR YOUR INNER COLLECTOR</small><h2>Collectors 14+</h2><p>Find your next shelf favourite.</p></div><span className="pp-shape pp-shape-collect" aria-hidden="true">✳</span><b aria-hidden="true">↗</b></Link></div>
    <section className="pp-wrap pp-section" id="ages"><div className="pp-section-heading"><div><p className="pp-eyebrow">GROW INTO SOMETHING WONDERFUL</p><h2>Every age. Every stage.</h2></div><p>Find a little joy for where they are now.</p></div><div className="pp-age-grid">{AGE_GROUPS.map((g) => <Link key={g.id} className={`pp-age-tile pp-${g.color}`} href={`/collections/toys?age=${g.id}`}><div className="pp-age-illustration"><Image src={`/playpuff/age-${g.id}.webp`} alt={`${g.name} play illustration`} width={640} height={640} sizes="(max-width: 767px) 45vw, 280px" /><div className="pp-age-illustration"><Image src={`/playpuff/age-${g.id}.webp`} alt={`${g.name} play illustration`} width={640} height={640} sizes="(max-width: 767px) 45vw, 280px" /><span className="pp-age-number">{g.label.replace("Ages ", "")}</span></div></div><h3>{g.name}</h3><span>{g.label} <b aria-hidden="true">↗</b></span></Link>)}</div><p className="pp-age-note">Every toy has its own age recommendation. Always check the product details before choosing.</p></section>
    <section className="pp-picks pp-section"><div className="pp-wrap"><div className="pp-section-heading"><div><p className="pp-eyebrow">A LITTLE SOMETHING TO LOVE</p><h2>PlayPuff Picks <span aria-hidden="true">✦</span></h2></div><Link href="/collections/toys" className="pp-text-link">Shop all finds ↗</Link></div><ToyPicks kids={grid(kids)} collectors={grid(collectors)} /></div></section>
    {categories.length > 0 && <section className="pp-wrap pp-section"><div className="pp-section-heading"><h2>So many ways to play.</h2></div><div className="pp-category-grid">{categories.map(c => <Link key={c.id} href={`/collections/toys?category=${c.handle}`}><span aria-hidden="true">✦</span><h3>{c.name}</h3><span>Explore →</span></Link>)}</div></section>}
    {!!collectors?.products.length && <section className="pp-wrap pp-section"><div className="pp-section-heading"><div><p className="pp-eyebrow">A PLACE FOR YOUR PASSION · 14+</p><h2>Collector’s Corner</h2></div><Link href="/collections/toys?audience=collectors">Explore the collection ↗</Link></div><div className="pp-product-grid">{collectors.products.slice(0, 4).map(p => <ToyCard key={p.id} product={p} />)}</div></section>}
    <section className="pp-wrap pp-story pp-section"><div className="pp-story-art" aria-hidden="true"><span>p</span><span>l</span><span>a</span><span>y</span><i>✦</i></div><div><p className="pp-eyebrow">HELLO, WE’RE PLAYPUFF.</p><h2>Never too little.<br />Never too grown-up.</h2><p>Play looks different for everyone. It’s a first discovery, a shared afternoon, or that perfect addition to your collection. There’s room for it all here.</p><Link className="pp-text-link" href="/pages/about">A little about us ↗</Link></div></section>
    <section className="pp-wrap pp-section pp-faq"><h2>A little help goes a long way.</h2>{[["How do I choose the right age?", "Explore our four age groups, then check the specific age recommendation and warnings on each product. Collectibles marked 14+ are not intended for younger children."], ["Where do you deliver?", "PlayPuff is being prepared for customers in the United States. Available shipping methods and charges are shown at checkout before payment."], ["Where can I find return information?", "Check our returns page for the current policy before placing an order."]].map(([q, a]) => <details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</section>
  </div>
}
